bg_default: &bg_default {stack: [{background: {color: 89b4fa55}}, {underline: {size: 3, color: 89dcebff}}]}

bg_time: &bg_time {stack: [{background: {color: 89b4fa33}}]}

bar:
  location: bottom
  height: 20
  background: 89b4fa11
  font: JetBrains Mono:pixelsize=13
  right-margin: 5

  right:
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: {string: {text: "{linear_volume}% ", foreground: f38ba8ff}}
              ~muted: {string: {text: "{linear_volume}% "}}
        content:

          list:
            items:
              - map:
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          icon == "audio-headset-bluetooth":
                            string: {text: "🎧"}
                        default:
                          - ramp:
                              tag: linear_volume
                              items:
                                - string: {text: "🔈"}
                                - string: {text: "🔉"}
                                - string: {text: "🔊"}
                    type == "source":
                      - string: {text: "🎙"}
              - map:
                  <<: *volume
    - clock:
        date-format: "[%a] [%d/%b/%Y]"
        time-format: "%l:%M %p"
        content:
          - string: {text: "{date}"}
          - string: {text: "{time}", deco: *bg_time}
            




  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 8
              right-margin: 10
              default: {string: {text: }}
              conditions:
                id == 1: {string: {text: 1}}
                id == 2: {string: {text: 2}}
                id == 3: {string: {text: 3}}
                id == 4: {string: {text: 4}}
                id == 5: {string: {text: 5}}
                id == 6: {string: {text: 6}}
                id == 7: {string: {text: 7}}
                id == 8: {string: {text: 8}}
                id == 9: {string: {text: 9}}

        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 0, color: ea6962ff}}


  center:
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{app-id}", foreground: 89dcebff}
                #- string: {text: ": {title}"}

