bg_default: &bg_default { stack: [
  { background: { color: cba6f750}},
  { underline: { size: 2, color: cba6f765}}
]}

bg_vol: &bg_vol { stack: [
  { background: { color: cba6f750}},
  { underline: { size: 2, color: cba6f765}}
]}

bg_cpu: &bg_cpu { stack: [
  { background: { color: cba6f760}},
  { underline: { size: 2, color: cba6f775}}
]}

bg_mem: &bg_mem { stack: [
  { background: { color: cba6f770}},
  { underline: { size: 2, color: cba6f785}}
]}

bg_clock: &bg_clock { stack: [
  { background: { color: cba6f780}},
  { underline: { size: 2, color: cba6f795}}
]}

bg_mute: &bg_mute { stack: [
  { background: { color: d20f39ff }},
]}

# fonts
awesome: &awesome Font Awesome 6 Free:style=solid:pixelsize=12

bar:
  location: top
  height: 20
  background: 1e1e2e00
  font: GeistMono:pixelsize=13
  right-margin: 4
  spacing: 4

  right:
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: {string: {text: "{linear_volume}% ",deco: *bg_mute}}
              ~muted: {string: {text: "{linear_volume}% "}}
        content:

          list:
            deco: *bg_vol
            on-click:
              wheel-up: "pactl set-sink-volume @DEFAULT_SINK@ +5%"
              wheel-down: "pactl set-sink-volume @DEFAULT_SINK@ -5%"
              left: "pactl set-sink-mute @DEFAULT_SINK@ toggle"
            items:
              - map:
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          icon == "audio-headset-bluetooth":
                            string: {text: "🎧"}
                        default:
                          - ramp:
                              tag: linear_volume
                              items:
                                - string: {text: " \uf026", font: *awesome}
                                - string: {text: " \uf027", font: *awesome}
                                - string: {text: " \uf028", font: *awesome}
                    type == "source":
                      - string: {text: " \uf130", font: *awesome}
              - map:
                  <<: *volume

    - cpu:
       anchors:
         ico_cpu: &ico_cpu { text: " \uf2db", font: *awesome }
       poll-interval: 3000
       content:
         map:
           conditions:
             id < 0:
              list:
                deco: *bg_cpu
                items:
                  - string: *ico_cpu

                  - string:
                      text: "{cpu}% " 

    - mem:
        anchors:
          ico_mem: &ico_mem { text: " \uf538", font: *awesome }
        poll-interval: 3500
        content:
          list:
            deco: *bg_mem
            items:
              - string: *ico_mem
              - string: {text: " {percent_used}% "}
      
    - clock:
        anchors:
          ico_time: &ico_time { text: " \uf017", font: *awesome }
          ico_date: &ico_date { text: " \uf073", font: *awesome }
        date-format: "%a %d/%b/%Y"
        time-format: "%l:%M %p"

        content:
          list:
            deco: *bg_clock
            items:
              - string: *ico_date
              - string: { text: "{date}" }
              - string: *ico_time
              - string: {text: "{time} "}     

    - removables:
        content:
          map:
            conditions:
              ~mounted:
                string:
                  on-click: udisksctl mount -b {device}
                  text: "{label}"
              mounted:
                string:
                  on-click: udisksctl unmount -b {device}
                  text: "{label}"
                  deco: {underline: {size: 2, color: ffffffff}}

            

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 8
              right-margin: 10
              default: {string: {text: }}
              conditions:
                id == 1: {string: {text: 1}}
                id == 2: {string: {text: 2}}
                id == 3: {string: {text: 3}}
                id == 4: {string: {text: 4}}
                id == 5: {string: {text: 5}}
                id == 6: {string: {text: 6}}
                id == 7: {string: {text: 7}}
                id == 8: {string: {text: 8}}
                id == 9: {string: {text: 9}}

        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 0, color: ea6962ff}}


  center:

    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{app-id}", foreground: a765f7ff}
                #- string: {text: ": {title}"}

