; for i3wm

[colors]
; Dracula Palette
dark = #282a36
lessdark = #44475a
white = #f8f8f2
darkblue = #6272a4
blue = #8be9fd
green = #50fa7b
orange = #ffb86c
pink = #ff79c6
purple = #bd93f9
red = #ff5555
yellow = #f1fa8c

; Default variables set to Dracula
background = ${colors.dark}
background-alt = ${colors.purple} 
foreground = ${colors.white}
primary = ${colors.purple}
secondary = ${colors.blue}
alert = ${colors.red}
disabled = ${colors.pink}
background-tra = #10282a36

[bar/pbari3]
width = 100%
height = 20

background = ${colors.background-tra}
foreground = ${colors.white}


modules-left = xworkspaces
modules-center = 
modules-right = xkeyboard  pulseaudio time

tray-position = right
tray-scale = 1.0
tray-background = ${colors.background-tra} 
tray-padding = 2
;tray-maxsize = 18


module-margin = 2

separator = "|"

font-0 = "Roboto:style=Bold:size=11;2"
font-1 = "FontAwesome6free:style=Solid:size=10;2"
font-2 = "Symbols Nerd Font:size=10;3"

[settings]
pseudo-transparency = true

;[module/powermenu]
;type = custom/menu

;expand-right = true

;format-spacing = 1

;label-open = " Session"

;label-close = "Close"
;label-close-foreground = ${colors.red}

;label-separator = |

;menu-0-0 = "Poweroff"
;menu-0-0-exec = menu-open-1

;menu-0-1 = "Reboot"
;menu-0-1-exec = menu-open-2

;menu-1-0 = "Poweroff"
;menu-1-0-exec = systemctl poweroff
;menu-1-1 = "Cancel"
;menu-1-1-exec = menu-open-0

;menu-2-0 = "Reboot"
;menu-2-0-exec = systemctl reboot
;menu-2-1 = "Cancel"
;menu-2-1-exec = menu-open-0


[module/time]
type = internal/date
; time = %d/%m/%Y - %l:%M %p
format-prefix = 
format-prefix-foreground = ${colors.green}
time = "%a %b %e %l:%M %p"
label = " %time%"
format-padding = 1
label-foreground = ${colors.white}

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = true
interval = 5
format-volume = "<ramp-volume> <label-volume>"

format-muted = <label-muted>
format-muted-prefix = 󰖁
format-muted-prefix-foreground = ${colors.red} 

label-volume = %percentage%%

label-muted = " muted"
label-muted-foreground = ${colors.white}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
click-right = pavucontrol
;format-font = 1
ramp-volume-foreground = #FCE9F1

[module/xworkspaces]
type = internal/xworkspaces
 
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1
 
label-occupied = %name%
label-occupied-padding = 1
 
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
 
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xkeyboard]
type = internal/xkeyboard

blacklist-0 = num lock
blacklist-1 = scroll lock

format-prefix = 󰌌
format-prefix-foreground = ${colors.blue}

label-layout = " %layout%"
label-layout-foreground = ${colors.white}
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}
